version: '3.6'
services:
  nginx:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80

  web:
    image: httpd
    ports:
      - "80:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: fluentd:24224
        tag: httpd.access

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: bitnami/elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: bitnami/kibana
    ports:
      - "5601:5601"

  clickhouse:
   image: yandex/clickhouse-server
   ports:
   - "8123:8123"
   - "9000:9000"
   - "9009:9009"
   ulimits:
    nproc: 65535
    nofile:
     soft: 262144
     hard: 262144

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  kafka:
    image: bitnami/kafka:2.6.0-debian-10-r69
    hostname: kafka-broker

  rabbitmq:
      image: rabbitmq:3-management-alpine
      volumes:
          - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
          - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
          - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
      environment:
          RABBITMQ_DEFAULT_USER: "rabbitmq"
          RABBITMQ_DEFAULT_PASS: "rabbitmq"
      ports:
          - 5672:5672
          - 15672:15672

  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    user: "104"