debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  [entryPoints.admin]
  address = ":8083"
    [entryPoints.admin.auth]
    [entryPoints.admin.auth.basic]
      users = [
        "test:$apr1$K8RmlfSZ$zOnm8Bdc7ohhbFVqUVkny."
      ]
[retry]

[api]
entryPoint = "admin"
dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "monitorg.com"
watch = true
exposedByDefault = false

[acme]
email = "root@k0d.ru"
entryPoint = "https"
storage = "/acme.json"
caServer = "https://acme-v02.api.letsencrypt.org/directory"
onHostRule = true
  [acme.dnsChallenge]
  provider = "vultr"
  delayBeforeCheck = 0
  [[acme.domains]]
   main = "monitorg.com"
  [[acme.domains]]
   main = "*.monitorg.com"